name: Check linter of source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  Check-Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Check linter
      run: npm run lint --workspaces
