name: Check linter of source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  Check-Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Check linter of client code
      working-directory: ./react_client
      run: |
        npm install
        npm run lint

    - name: Check linter of server code
      working-directory: ./react_server
      run: |
        npm install
        npm run lint
